<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gaji extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gaji_model');
        $this->load->model('Absensi_model');
        $this->load->library('form_validation');
        $this->load->library('ion_auth');

        if (!$this->ion_auth->logged_in())
        {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        }
    }

    public function index()
    {
        $gaji = $this->Gaji_model->get_all();

        $data = array(
            'judul_halaman' => 'Data Gaji',
            'gaji_data' => $gaji
        );

        $this->load->view('templates/header', $data);
        $this->load->view('templates/sidebar', $data);
        $this->load->view('gaji_list_view', $data);
        $this->load->view('templates/footer', $data);
    }

    public function detail($id)
    {
        $gaji = $this->Gaji_model->get_gaji_id($id);
        $absen = $this->Absensi_model->get_hadir_id($id);
        
        $data = array(
            'judul_halaman' => 'Detail Gaji',
            'gaji_data' => $gaji,
            'absen' => $absen
        );

        $this->load->view('templates/header', $data);
        $this->load->view('templates/sidebar', $data);
        $this->load->view('gaji_list_detail_view', $data);
        $this->load->view('templates/footer', $data);
    }

}

/* End of file Gaji.php */
/* Location: ./application/controllers/Gaji.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-10 17:52:35 */
/* http://harviacode.com */