<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gaji_model extends CI_Model
{

    public $table = 'gaji';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }



    function get_all()

    {
        $sql = 'SELECT  `karyawan`.`nip`,
                        `karyawan`.`nama`,
                        `jabatan`.`gaji_pokok`,
                        `karyawan`.`anak`,
                        `karyawan`.`status`,
                        `karyawan`.`slip`,
                        (SELECT `tunjangan`.`uang_tunjangan` FROM `tunjangan` WHERE `tunjangan`.`nama_tunjangan` = "Istri") AS st,
                        (SELECT `tunjangan`.`uang_tunjangan` FROM `tunjangan` WHERE `tunjangan`.`nama_tunjangan` = "Anak") AS an, 
                        `tunjangan`.`uang_tunjangan`,
                        SUM(`tunjangan`.`uang_tunjangan`) AS biaya 
                FROM `karyawan`
                LEFT JOIN `jabatan` ON `karyawan`.`jabatan` = `jabatan`.`nama_jabatan`
                LEFT JOIN `tunjangan_karyawan` ON `karyawan`.nip       = `tunjangan_karyawan`.`id_karyawan`
                LEFT JOIN `tunjangan` ON `tunjangan_karyawan`.`tujangan` = `tunjangan`.`nama_tunjangan`
                GROUP BY `karyawan`.`nip` ORDER BY `karyawan`.`nip`
        ' ;
        $query = $this->db->query($sql);
        return $query->result();
    }

    function get_gaji_id($id)
    {
        $sql = "SELECT  `karyawan`.`nip`,
                        `karyawan`.`nama`,
                        `jabatan`.`gaji_pokok`,
                        `karyawan`.`anak`,
                        `karyawan`.`status`,
                        `karyawan`.`slip`,
                        (SELECT `tunjangan`.`uang_tunjangan` FROM `tunjangan` WHERE `tunjangan`.`nama_tunjangan` = 'Istri') AS st,
                        (SELECT `tunjangan`.`uang_tunjangan` FROM `tunjangan` WHERE `tunjangan`.`nama_tunjangan` = 'Anak') AS an, 
                        `tunjangan`.`uang_tunjangan`,
                        SUM(`tunjangan`.`uang_tunjangan`) AS biaya 
                FROM `karyawan`
                LEFT JOIN `jabatan` ON `karyawan`.`jabatan` = `jabatan`.`nama_jabatan`
                LEFT JOIN `tunjangan_karyawan` ON `karyawan`.`nip` = `tunjangan_karyawan`.`id_karyawan`
                LEFT JOIN `tunjangan` ON `tunjangan_karyawan`.`tujangan` = `tunjangan`.`nama_tunjangan`
                WHERE `karyawan`.`nip` = '$id'
                GROUP BY `karyawan`.`nip` ORDER BY `karyawan`.`nip`
        " ;
        $query = $this->db->query($sql);
        return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('nip', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('gaji_pokok', $q);
    	$this->db->or_like('tunjangan', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('nip', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('gaji_pokok', $q);
    	$this->db->or_like('tunjangan', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }



}

/* End of file Gaji_model.php */
/* Location: ./application/models/Gaji_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-10 17:52:35 */
/* http://harviacode.com */