<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Karyawan_model extends CI_Model
{

    public $table = 'karyawan';
    public $id = 'id';
    public $nip = 'nip';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->nip, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('nip', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('jabatan', $q);
    	$this->db->or_like('jk', $q);
    	$this->db->or_like('kota_lahir', $q);
    	$this->db->or_like('tanggal_lahir', $q);
    	$this->db->or_like('agama', $q);
    	$this->db->or_like('alamat', $q);
    	$this->db->or_like('email', $q);
    	$this->db->or_like('telepon', $q);
    	$this->db->or_like('foto', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('anak', $q);
        $this->db->or_like('kk', $q);
        $this->db->or_like('slip', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('nip', $q);
    	$this->db->or_like('nama', $q);
    	$this->db->or_like('jabatan', $q);
    	$this->db->or_like('jk', $q);
    	$this->db->or_like('kota_lahir', $q);
    	$this->db->or_like('tanggal_lahir', $q);
    	$this->db->or_like('agama', $q);
    	$this->db->or_like('alamat', $q);
    	$this->db->or_like('email', $q);
    	$this->db->or_like('telepon', $q);
    	$this->db->or_like('foto', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('anak', $q);
        $this->db->or_like('kk', $q);
        $this->db->or_like('slip', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function jumlah_karyawan()
    {   
        $query = $this->db->get('karyawan');
        if($query->num_rows()>0)
        {
          return $query->num_rows();
        }
        else
        {
          return 0;
        }
    }

}

/* End of file Karyawan_model.php */
/* Location: ./application/models/Karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-01 18:48:42 */
/* http://harviacode.com */