<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tunjangan_karyawan_model extends CI_Model
{

    public $table  = 'tunjangan_karyawan';
    public $table2 = 'karyawan'; 
    public $id = 'id';
    public $id_karyawan;
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function read()
    {
        $sql = 'SELECT *,
                `tunjangan`.`uang_tunjangan`, 
                GROUP_CONCAT(DISTINCT(tujangan)) AS "list_tunjangan",
                COUNT(*) AS "jumlah_tunjangan",
                SUM(uang_tunjangan) AS biaya 
                FROM `tunjangan_karyawan` 
                JOIN `karyawan` ON `karyawan`.`nip` = `tunjangan_karyawan`.`id_karyawan` 
                JOIN `tunjangan` ON `tunjangan_karyawan`.`tujangan` = `tunjangan`.`nama_tunjangan`
                GROUP BY id_karyawan ORDER BY `id_karyawan`' ;
        $query = $this->db->query($sql);
        return $query->result();
    }

    // public function read_nama()
    // {
        //SCRIPT JOIN
        // $query = "
                    // SELECT `karyawan`.`nama`
                    // FROM `karyawan` JOIN `tunjangan_karyawan`
                    // ON `karyawan`.`nip` = `tunjangan_karyawan`.`id_karyawan`
                 // ";
        // return $this->db->query($query)->result_array();
    // }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->or_where('id_karyawan', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('id_karyawan', $q);
    	$this->db->or_like('tujangan', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('id_karyawan', $q);
    	$this->db->or_like('tujangan', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        // $this->db->where($this->id, $id);
        $this->db->where('id_karyawan', $id);
        $this->db->delete($this->table);
    }

    // function delete()
    // {
    //     $sql = sprintf("DELETE FROM tunjangan_karyawan WHERE id_karyawan='%s' ",
    //             $this->id_karyawan);
    //     $this->db->query($sql);
    // }

}

/* End of file Tunjangan_karyawan_model.php */
/* Location: ./application/models/Tunjangan_karyawan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-06 16:35:05 */
/* http://harviacode.com */